### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by picchiosat** [yuvelq/TG_Count#1]
Many thanks for your work.
This system only works if server and dashboard are on the same server because you have to read "freedmr.log".
If server and dashboarsh are on different servers would it be possible to read a "URL" instead of a local file?

Roby IV3JDV

**Comment by yuvelq** [comment]
Hi Roby, let me think on that, I think that for that particular case it will be easier adapt the script to pull the information from the HBMon logbook.

**Comment by yuvelq** [comment]
Hi Roby, Now the script will work with 'lastheard.log' from HBMonV2.
